import type { DataType } from "./schema";

export const dummyData: DataType[] = [
    {
        id: "1",
        arah: "masuk",
        bank: "bni",
        kategori: "sosial",
        date: 1664201600000,
        money: 100,
        note: "note1",
    },
    {
        id: "2",
        arah: "masuk",
        bank: "bni",
        kategori: "sosial",
        date: 1711985387508,
        money: 100,
        note: "what",
    },
    {
        id: "3",
        arah: "keluar",
        bank: "mandiri",
        kategori: "sosial",
        date: 1764201600000,
        money: 100,
        note: "he",
    },
    {
        id: "4",
        arah: "masuk",
        bank: "mandiri",
        kategori: "pendidikan",
        date: 1764201600000,
        money: 103,
        note: "mkay",
    },
    {
        id: "100",
        arah: "keluar",
        bank: "bni",
        kategori: "sosial",
        date: 1714201600000,
        money: 30,
        note: "bruh",
    },
    {
        id: "1",
        arah: "masuk",
        bank: "bni",
        kategori: "sosial",
        date: 1664201600000,
        money: 100,
        note: "note1",
    },
    {
        id: "2",
        arah: "masuk",
        bank: "bni",
        kategori: "sosial",
        date: 1711985387508,
        money: 100,
        note: "what",
    },
    {
        id: "3",
        arah: "keluar",
        bank: "mandiri",
        kategori: "sosial",
        date: 1764201600000,
        money: 100,
        note: "he",
    },
    {
        id: "4",
        arah: "masuk",
        bank: "mandiri",
        kategori: "pendidikan",
        date: 1764201600000,
        money: 103,
        note: "mkay",
    },
    {
        id: "100",
        arah: "keluar",
        bank: "bni",
        kategori: "sosial",
        date: 1714201600000,
        money: 30,
        note: "bruh",
    },
];
